### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/weather-app-api#2]
Add some cool features in this project or create issue for new feature.

**Comment by Pritam0077** [comment]
I would like to display temperature in Fahrenheit can you assign it to me

**Comment by codemaniac-sahil** [comment]
@Pritam0077 it will be great if you ask the user whether he wants to convert the temperature into Fahrenheit.

**Comment by Pritam0077** [comment]
ok i will try to add button that will change it to farenheit

**Comment by codemaniac-sahil** [comment]
Okay I am assigning this issue to you
