### ISSUE TITLE
Enhancing the select option UI of Alarm section in clock

### ISSUE THREAD

**Issue by snehafarkya** [codemaniac-sahil/weather-app-api#20]
Hey @codemaniac-sahil ! I have gone through this website and found out that there is a need to upgrade the UI. 
I would like to change the `select hours and minutes option` UI in the clock. 

This is how it will look after change 👇 
![image](https://user-images.githubusercontent.com/63949465/195076902-2da5054a-1648-46fd-a470-7baaea0435ce.png)
### Kindly assign me this issue under hactoberfest!

**Comment by codemaniac-sahil** [comment]
okay @snehafarkya you can work on this case now.

**Comment by codemaniac-sahil** [comment]
@snehafarkya I think you are on the wrong repository, but you can send the PR on that repository

**Comment by snehafarkya** [comment]
Can you share the link of that repo?

**Comment by codemaniac-sahil** [comment]
@snehafarkya this is the repo link https://github.com/codemaniac-sahil/javascript-clock

**Comment by codemaniac-sahil** [comment]
I am closing this issue.
