### ISSUE TITLE
Weather result ui enhancement

### ISSUE THREAD

**Issue by jsvigneshkanna** [codemaniac-sahil/weather-app-api#25]
I would like to enhance the weather result ui as a card with image based of temperature

Please assign me this feature

**Comment by codemaniac-sahil** [comment]
@jsvigneshkanna You can start working on this issue

**Comment by tejus0** [comment]
hey @codemaniac-sahil  Is this issue resolved ? if yes then the created ui is same as visible in website ? 

![image](https://user-images.githubusercontent.com/76488943/196994237-87b7c7cf-0af0-47d4-b8fc-0fe43fb95664.png)

**Comment by codemaniac-sahil** [comment]
yes @tejus0
