### ISSUE TITLE
bug: Footer sticks at bottom of viewport height.

### ISSUE THREAD

**Issue by ranjankuldeep** [codemaniac-sahil/weather-app-api#28]
Footer should be at the bottom of the page, not the bottom of the viewport height.
It sticks there and hides the content behind it.

This gives a bad user experience, page content should be visible to the available viewport.

<img width="1440" alt="Screenshot 2022-10-15 at 12 19 33 PM" src="https://user-images.githubusercontent.com/95350799/195973479-849e5144-44a9-46ad-ac27-fa30996b0451.png">

**Comment by ranjankuldeep** [comment]
## Please assign it to me.
### I know the solution.

@codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
@ranjankuldeep you can start working on this issue

**Comment by tejus0** [comment]
hey @codemaniac-sahil is it fixed or i can fix this issue ?

**Comment by codemaniac-sahil** [comment]
@tejus0 it is resolved
