### ISSUE TITLE
Making the UI better for user experience

### ISSUE THREAD

**Issue by NayakPenguin** [codemaniac-sahil/weather-app-api#8]
I am myself trying to contribute to this, but since the UI is not very much appealing I am thinking of making it encouraging for the users.

**Comment by codemaniac-sahil** [comment]
Okay @Nayaker, this issue is your.

**Comment by NayakPenguin** [comment]
@codemaniac-sahil really appreciate you for assigning. I have changed the landing UI, now I am working on the bottom part which looks a bit empty. Might add some weather news or something. Later on, I will generate a pull request for you to merge the code changes. 
Here is the update : 
<img width="1440" alt="Screenshot 2022-10-02 at 5 28 05 PM" src="https://user-images.githubusercontent.com/93304796/193452784-82619f7b-1626-4e1e-a1c4-09195f51095b.png">

**Comment by codemaniac-sahil** [comment]
This is tooooooooo good

**Comment by codemaniac-sahil** [comment]
generate PR fast

**Comment by NayakPenguin** [comment]
Yeah just making few changes more changes

**Comment by codemaniac-sahil** [comment]
Okay @Nayaker

**Comment by codemaniac-sahil** [comment]
https://github.com/codemaniac-sahil/currency_converter_react/issues/6
Are you able to resolve this.

**Comment by NayakPenguin** [comment]
Actually right now I am working on the UI part, I will soon start working on JS aswell.

**Comment by NayakPenguin** [comment]
@codemaniac-sahil please merge the PR which I just made.

**Comment by codemaniac-sahil** [comment]
already done
